server:
  port: 9991

#hello.springmvc ???? ? ?? ?? ?? ??
#?? ??? trace, debug ??, ?? ??? debug, ?? ????? info ???? ??? ?? (default=info, root ? ??? info, root ? debug, trace? ??? ?? ??? ?? ??)
logging:
  level:
    dev.riss.springmvc: debug  # dev.riss.springmvc ?? ???? ?? ??? info ?? ?? ?? ?